. ~/dotfiles/shell/profile

# cuda path
if [ -d "/usr/local/cuda" ] ; then
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
    export CUDA_HOME=/usr/local/cuda
    path=(
        $CUDA_HOME/bin(N-/)
        $path
    )
fi

