" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
"if has('gui_gtk2')
"  set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
"else
"  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
"endif

" If you want to run gvim with a dark background, try using a different
" colorscheme or running 'gvim -reverse'.
" http://www.cs.cmu.edu/~maverick/VimColorSchemeTest/ has examples and
" downloads for the colorschemes on vim.org

" Source a global configuration file if available
"if filereadable("/etc/vim/gvimrc.local")
"  source /etc/vim/gvimrc.local
"endif

set lines=50
set columns=82

let fontname="Ricty Diminished "
let &guifont=fontname."13"
" set size command
command! -nargs=1 FontSize let &guifont=fontname.<args>

" disable toolbar
set guioptions-=T

" enable popup
set mousemodel=popup

