if &encoding !=# "utf-8"
    set encoding=utf-8
endif
scriptencoding utf-8

if has('nvim')
    let $VIMDIR = expand('$HOME/.config/nvim')
    let $VIMTMP = expand('$HOME/.local/share/nvim')
else
    let $VIMDIR = expand('$HOME/.vim')
    let $VIMTMP = expand('$HOME/.local/share/vim')
endif
if ! isdirectory($VIMTMP)
    call mkdir($VIMTMP)
endif

let $HASPLUGIN = filereadable($VIMDIR.'/autoload/plug.vim')
if $HASPLUGIN
    source ~/dotfiles/vim/vimrcs/plugins.vim
endif
source ~/dotfiles/vim/vimrcs/common.vim
