if &encoding !=# "utf-8"
    set encoding=utf-8
endif
scriptencoding utf-8

if has('nvim')
    let $VIMDIR = expand('$HOME/.config/nvim')
    let $VIMTMP = expand('$HOME/.local/share/nvim')
else
    let $VIMDIR = expand('$HOME/.vim')
    let $VIMTMP = expand('$HOME/.local/share/vim')
endif
if ! isdirectory($VIMTMP)
    call mkdir($VIMTMP)
endif


" Utility
" -------

let g:system_open = "invalid_command"
if has('unix')
    if has ('macunix')
        let g:system_open = "open"
    else
        let g:system_open = "xdg-open"
    endif
endif

function! Chomp(string)
    return substitute(a:string, '\n\+$', '', '')
endfunction


" Load scripts
" ------------

source ~/dotfiles/vim/vimrcs/common.vim
let $HASPLUGIN = filereadable($VIMDIR.'/autoload/plug.vim') || filereadable($VIMTMP.'/site/autoload/plug.vim')
if has('nvim') && $HASPLUGIN
    luafile ~/dotfiles/vim/vimrcs/plugins.lua
endif
" if $HASPLUGIN
"     source ~/dotfiles/vim/vimrcs/plugins.vim
" endif
